name: Security

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: npm ci
    - run: npm audit --audit-level=high
    - name: Gitleaks
      uses: gitleaks/gitleaks-action@v2
